<?php
return [
    [
        "id" => 1,
        "title" => "Monolocale accogliente nel centro storico",
        "rooms" => 1,
        "beds" => 1,
        "bathrooms" => 1,
        "apartment_size" => 35,
        "address" => "Via Roma, 15, Torino, Piemonte, Italia",
        "latitude" => 45.070312,
        "longitude" => 7.686856,
        "image" => "https://www.pexels.com/it-it/foto/monolocale-accogliente-1457842/",
        "is_visible" => true
    ],
    [
        "id" => 2,
        "title" => "Trilocale con terrazza vista mare",
        "rooms" => 3,
        "beds" => 2,
        "bathrooms" => 1,
        "apartment_size" => 85,
        "address" => "Via Lungomare, 10, Palermo, Sicilia, Italia",
        "latitude" => 38.115687,
        "longitude" => 13.361267,
        "image" => "https://www.pexels.com/it-it/foto/trilocale-vista-mare-221506/",
        "is_visible" => true
    ],
    [
        "id" => 3,
        "title" => "Bilocale moderno vicino alla stazione",
        "rooms" => 2,
        "beds" => 1,
        "bathrooms" => 1,
        "apartment_size" => 50,
        "address" => "Piazza Garibaldi, 12, Napoli, Campania, Italia",
        "latitude" => 40.851775,
        "longitude" => 14.268124,
        "image" => "https://www.pexels.com/it-it/foto/bilocale-moderno-534151/",
        "is_visible" => false
    ],
    [
        "id" => 4,
        "title" => "Villa di lusso con piscina privata",
        "rooms" => 5,
        "beds" => 4,
        "bathrooms" => 3,
        "apartment_size" => 250,
        "address" => "Via della Pergola, 7, Firenze, Toscana, Italia",
        "latitude" => 43.76956,
        "longitude" => 11.255814,
        "image" => "https://www.pexels.com/it-it/foto/villa-lusso-piscina-1643383/",
        "is_visible" => true
    ],
    [
        "id" => 5,
        "title" => "Loft industriale nel cuore della città",
        "rooms" => 2,
        "beds" => 1,
        "bathrooms" => 1,
        "apartment_size" => 70,
        "address" => "Via Alessandro Volta, 8, Milano, Lombardia, Italia",
        "latitude" => 45.465421,
        "longitude" => 9.185924,
        "image" => "https://www.pexels.com/it-it/foto/loft-industriale-210604/",
        "is_visible" => true
    ],
    [
        "id" => 6,
        "title" => "Attico con vista mozzafiato",
        "rooms" => 4,
        "beds" => 2,
        "bathrooms" => 2,
        "apartment_size" => 120,
        "address" => "Via Michelangelo Buonarroti, 22, Bologna, Emilia-Romagna, Italia",
        "latitude" => 44.494887,
        "longitude" => 11.342616,
        "image" => "https://www.pexels.com/it-it/foto/attico-panoramico-276724/",
        "is_visible" => true
    ],
    [
        "id" => 7,
        "title" => "Rustico immerso nella campagna",
        "rooms" => 3,
        "beds" => 2,
        "bathrooms" => 1,
        "apartment_size" => 95,
        "address" => "Contrada San Lorenzo, 5, Siracusa, Sicilia, Italia",
        "latitude" => 36.951474,
        "longitude" => 15.089849,
        "image" => "https://www.pexels.com/it-it/foto/casetta-rustica-campagna-279746/",
        "is_visible" => true
    ],
    [
        "id" => 8,
        "title" => "Appartamento moderno vicino al mare",
        "rooms" => 3,
        "beds" => 2,
        "bathrooms" => 1,
        "apartment_size" => 80,
        "address" => "Viale Regina Elena, 10, Cagliari, Sardegna, Italia",
        "latitude" => 39.217142,
        "longitude" => 9.116849,
        "image" => "https://www.pexels.com/it-it/foto/appartamento-moderno-mare-162561/",
        "is_visible" => true
    ],
    [
        "id" => 9,
        "title" => "Bilocale tranquillo con giardino privato",
        "rooms" => 2,
        "beds" => 1,
        "bathrooms" => 1,
        "apartment_size" => 55,
        "address" => "Via dell'Ulivo, 3, Perugia, Umbria, Italia",
        "latitude" => 43.110716,
        "longitude" => 12.390828,
        "image" => "https://www.pexels.com/it-it/foto/bilocale-giardino-790010/",
        "is_visible" => true
    ],
    [
        "id" => 10,
        "title" => "Appartamento vintage nel centro storico",
        "rooms" => 3,
        "beds" => 2,
        "bathrooms" => 1,
        "apartment_size" => 85,
        "address" => "Via San Marco, 45, Venezia, Veneto, Italia",
        "latitude" => 45.434123,
        "longitude" => 12.338768,
        "image" => "https://www.pexels.com/it-it/foto/appartamento-vintage-284510/",
        "is_visible" => false
    ],
    [
        "id" => 11,
        "title" => "Villa immersa nella natura con piscina",
        "rooms" => 6,
        "beds" => 5,
        "bathrooms" => 3,
        "apartment_size" => 300,
        "address" => "Via Collina Verde, 18, Assisi, Umbria, Italia",
        "latitude" => 43.070703,
        "longitude" => 12.619597,
        "image" => "https://www.pexels.com/it-it/foto/villa-natura-piscina-1643383/",
        "is_visible" => true
    ],
    [
        "id" => 12,
        "title" => "Monolocale artistico in quartiere bohemien",
        "rooms" => 1,
        "beds" => 1,
        "bathrooms" => 1,
        "apartment_size" => 40,
        "address" => "Via Margutta, 51, Roma, Lazio, Italia",
        "latitude" => 41.906347,
        "longitude" => 12.479073,
        "image" => "https://www.pexels.com/it-it/foto/monolocale-artistico-145796/",
        "is_visible" => true
    ],
    [
        "id" => 13,
        "title" => "Appartamento storico con soffitti affrescati",
        "rooms" => 4,
        "beds" => 3,
        "bathrooms" => 2,
        "apartment_size" => 150,
        "address" => "Piazza della Signoria, 10, Firenze, Toscana, Italia",
        "latitude" => 43.769795,
        "longitude" => 11.255236,
        "image" => "https://www.pexels.com/it-it/foto/soffitti-affrescati-249601/",
        "is_visible" => true
    ],
    [
        "id" => 14,
        "title" => "Loft minimalista con ampie vetrate",
        "rooms" => 2,
        "beds" => 1,
        "bathrooms" => 1,
        "apartment_size" => 75,
        "address" => "Via Dante, 9, Milano, Lombardia, Italia",
        "latitude" => 45.465558,
        "longitude" => 9.185717,
        "image" => "https://www.pexels.com/it-it/foto/loft-minimalista-789003/",
        "is_visible" => false
    ],
    [
        "id" => 15,
        "title" => "Rustico con camino e vista panoramica",
        "rooms" => 3,
        "beds" => 2,
        "bathrooms" => 1,
        "apartment_size" => 80,
        "address" => "Via della Vigna, 15, Siena, Toscana, Italia",
        "latitude" => 43.318331,
        "longitude" => 11.331194,
        "image" => "https://www.pexels.com/it-it/foto/rustico-camino-163207/",
        "is_visible" => true
    ],
    [
        "id" => 16,
        "title" => "Villa storica con giardino e piscina",
        "rooms" => 6,
        "beds" => 5,
        "bathrooms" => 3,
        "apartment_size" => 320,
        "address" => "Via dei Cipressi, 8, Lucca, Toscana, Italia",
        "latitude" => 43.843017,
        "longitude" => 10.501598,
        "image" => "https://www.pexels.com/it-it/foto/villa-storica-piscina-312587/",
        "is_visible" => true
    ],
    [
        "id" => 17,
        "title" => "Bilocale luminoso a due passi dal centro",
        "rooms" => 2,
        "beds" => 1,
        "bathrooms" => 1,
        "apartment_size" => 50,
        "address" => "Via Garibaldi, 11, Genova, Liguria, Italia",
        "latitude" => 44.411854,
        "longitude" => 8.932600,
        "image" => "https://www.pexels.com/it-it/foto/bilocale-luminoso-292102/",
        "is_visible" => true
    ],
    [
        "id" => 18,
        "title" => "Appartamento moderno in zona residenziale",
        "rooms" => 3,
        "beds" => 2,
        "bathrooms" => 2,
        "apartment_size" => 100,
        "address" => "Via Dei Mille, 20, Catania, Sicilia, Italia",
        "latitude" => 37.507877,
        "longitude" => 15.083030,
        "image" => "https://www.pexels.com/it-it/foto/appartamento-moderno-411534/",
        "is_visible" => true
    ],
    [
        "id" => 19,
        "title" => "Monolocale economico vicino all'università",
        "rooms" => 1,
        "beds" => 1,
        "bathrooms" => 1,
        "apartment_size" => 30,
        "address" => "Via Zamboni, 32, Bologna, Emilia-Romagna, Italia",
        "latitude" => 44.494981,
        "longitude" => 11.343034,
        "image" => "https://www.pexels.com/it-it/foto/monolocale-economico-146378/",
        "is_visible" => false
    ],
    [
        "id" => 20,
        "title" => "Attico esclusivo con terrazza panoramica",
        "rooms" => 4,
        "beds" => 3,
        "bathrooms" => 2,
        "apartment_size" => 200,
        "address" => "Piazza San Marco, 20, Venezia, Veneto, Italia",
        "latitude" => 45.434046,
        "longitude" => 12.338895,
        "image" => "https://www.pexels.com/it-it/foto/attico-esclusivo-111205/",
        "is_visible" => true
    ],
    [
        "id" => 21,
        "title" => "Casa colonica con vigneto",
        "rooms" => 5,
        "beds" => 4,
        "bathrooms" => 2,
        "apartment_size" => 200,
        "address" => "Via del Vino, 12, Chianti, Toscana, Italia",
        "latitude" => 43.5833,
        "longitude" => 11.3167,
        "image" => "https://www.pexels.com/it-it/foto/casa-vigneto-249120/",
        "is_visible" => true
    ],
    [
        "id" => 22,
        "title" => "Appartamento accogliente con vista lago",
        "rooms" => 3,
        "beds" => 2,
        "bathrooms" => 1,
        "apartment_size" => 80,
        "address" => "Via Lago Maggiore, 18, Stresa, Piemonte, Italia",
        "latitude" => 45.884945,
        "longitude" => 8.537226,
        "image" => "https://www.pexels.com/it-it/foto/appartamento-vista-lago-409320/",
        "is_visible" => true
    ],
    [
        "id" => 23,
        "title" => "Monolocale trendy vicino al porto",
        "rooms" => 1,
        "beds" => 1,
        "bathrooms" => 1,
        "apartment_size" => 35,
        "address" => "Via del Porto, 10, Bari, Puglia, Italia",
        "latitude" => 41.120654,
        "longitude" => 16.869444,
        "image" => "https://www.pexels.com/it-it/foto/monolocale-trendy-145612/",
        "is_visible" => true
    ],
    [
        "id" => 24,
        "title" => "Loft con cucina open-space",
        "rooms" => 2,
        "beds" => 1,
        "bathrooms" => 1,
        "apartment_size" => 60,
        "address" => "Via Garibaldi, 22, Padova, Veneto, Italia",
        "latitude" => 45.406434,
        "longitude" => 11.876761,
        "image" => "https://www.pexels.com/it-it/foto/loft-cucina-openspace-128751/",
        "is_visible" => true
    ],
    [
        "id" => 25,
        "title" => "Appartamento in villa storica",
        "rooms" => 4,
        "beds" => 3,
        "bathrooms" => 2,
        "apartment_size" => 120,
        "address" => "Via della Villa, 6, Como, Lombardia, Italia",
        "latitude" => 45.808059,
        "longitude" => 9.085176,
        "image" => "https://www.pexels.com/it-it/foto/appartamento-villa-storica-111521/",
        "is_visible" => true
    ],
    [
        "id" => 26,
        "title" => "Bilocale moderno con terrazzo",
        "rooms" => 2,
        "beds" => 1,
        "bathrooms" => 1,
        "apartment_size" => 50,
        "address" => "Via Della Libertà, 32, Palermo, Sicilia, Italia",
        "latitude" => 38.123168,
        "longitude" => 13.360567,
        "image" => "https://www.pexels.com/it-it/foto/bilocale-moderno-terrazzo-147821/",
        "is_visible" => true
    ],
    [
        "id" => 27,
        "title" => "Villa con uliveto privato",
        "rooms" => 6,
        "beds" => 5,
        "bathrooms" => 3,
        "apartment_size" => 300,
        "address" => "Contrada Uliveto, 14, Ostuni, Puglia, Italia",
        "latitude" => 40.729631,
        "longitude" => 17.577530,
        "image" => "https://www.pexels.com/it-it/foto/villa-uliveto-322587/",
        "is_visible" => true
    ],
    [
        "id" => 28,
        "title" => "Rustico ristrutturato con camino",
        "rooms" => 3,
        "beds" => 2,
        "bathrooms" => 1,
        "apartment_size" => 85,
        "address" => "Strada della Quercia, 7, Arezzo, Toscana, Italia",
        "latitude" => 43.463282,
        "longitude" => 11.879517,
        "image" => "https://www.pexels.com/it-it/foto/rustico-camino-364282/",
        "is_visible" => false
    ],
    [
        "id" => 29,
        "title" => "Attico elegante in centro",
        "rooms" => 5,
        "beds" => 3,
        "bathrooms" => 2,
        "apartment_size" => 180,
        "address" => "Piazza del Popolo, 15, Roma, Lazio, Italia",
        "latitude" => 41.910241,
        "longitude" => 12.476849,
        "image" => "https://www.pexels.com/it-it/foto/attico-elegante-197401/",
        "is_visible" => true
    ],
    [
        "id" => 30,
        "title" => "Casale in collina con piscina",
        "rooms" => 4,
        "beds" => 3,
        "bathrooms" => 2,
        "apartment_size" => 120,
        "address" => "Via Collina, 5, Fiesole, Toscana, Italia",
        "latitude" => 43.806530,
        "longitude" => 11.292043,
        "image" => "https://www.pexels.com/it-it/foto/casale-piscina-163452/",
        "is_visible" => true
    ],
    [
        "id" => 31,
        "title" => "Monolocale chic in zona pedonale",
        "rooms" => 1,
        "beds" => 1,
        "bathrooms" => 1,
        "apartment_size" => 30,
        "address" => "Via Toledo, 88, Napoli, Campania, Italia",
        "latitude" => 40.847058,
        "longitude" => 14.252504,
        "image" => "https://www.pexels.com/it-it/foto/monolocale-chic-164214/",
        "is_visible" => true
    ],
    [
        "id" => 32,
        "title" => "Villa panoramica sulle colline",
        "rooms" => 6,
        "beds" => 5,
        "bathrooms" => 3,
        "apartment_size" => 350,
        "address" => "Via delle Colline, 21, Urbino, Marche, Italia",
        "latitude" => 43.723042,
        "longitude" => 12.636789,
        "image" => "https://www.pexels.com/it-it/foto/villa-panoramica-268412/",
        "is_visible" => true
    ],
    [
        "id" => 33,
        "title" => "Bilocale con patio privato",
        "rooms" => 2,
        "beds" => 1,
        "bathrooms" => 1,
        "apartment_size" => 45,
        "address" => "Via dei Fiori, 10, Rimini, Emilia-Romagna, Italia",
        "latitude" => 44.063804,
        "longitude" => 12.568454,
        "image" => "https://www.pexels.com/it-it/foto/bilocale-patio-234561/",
        "is_visible" => true
    ],
    [
        "id" => 34,
        "title" => "Rustico in pietra con giardino",
        "rooms" => 4,
        "beds" => 3,
        "bathrooms" => 2,
        "apartment_size" => 110,
        "address" => "Contrada Pietraia, 6, Matera, Basilicata, Italia",
        "latitude" => 40.664354,
        "longitude" => 16.608392,
        "image" => "https://www.pexels.com/it-it/foto/rustico-pietra-142536/",
        "is_visible" => false
    ],
    [
        "id" => 35,
        "title" => "Appartamento moderno fronte mare",
        "rooms" => 3,
        "beds" => 2,
        "bathrooms" => 1,
        "apartment_size" => 90,
        "address" => "Lungomare Cristoforo Colombo, 20, Crotone, Calabria, Italia",
        "latitude" => 39.080307,
        "longitude" => 17.123498,
        "image" => "https://www.pexels.com/it-it/foto/appartamento-mare-224365/",
        "is_visible" => true
    ],
    [
        "id" => 36,
        "title" => "Casa rustica con vista sulle Dolomiti",
        "rooms" => 5,
        "beds" => 4,
        "bathrooms" => 2,
        "apartment_size" => 180,
        "address" => "Via delle Alpi, 15, Cortina d'Ampezzo, Veneto, Italia",
        "latitude" => 46.540474,
        "longitude" => 12.135664,
        "image" => "https://www.pexels.com/it-it/foto/casa-dolomiti-287462/",
        "is_visible" => true
    ],
    [
        "id" => 37,
        "title" => "Monolocale eco-friendly",
        "rooms" => 1,
        "beds" => 1,
        "bathrooms" => 1,
        "apartment_size" => 28,
        "address" => "Via Natura, 5, Bolzano, Trentino-Alto Adige, Italia",
        "latitude" => 46.498294,
        "longitude" => 11.354758,
        "image" => "https://www.pexels.com/it-it/foto/monolocale-eco-221456/",
        "is_visible" => false
    ],
    [
        "id" => 38,
        "title" => "Villa moderna con piscina e vista mare",
        "rooms" => 6,
        "beds" => 5,
        "bathrooms" => 3,
        "apartment_size" => 400,
        "address" => "Contrada Sole, 8, Tropea, Calabria, Italia",
        "latitude" => 38.676571,
        "longitude" => 15.899112,
        "image" => "https://www.pexels.com/it-it/foto/villa-moderna-223654/",
        "is_visible" => true
    ],
    [
        "id" => 39,
        "title" => "Appartamento storico con cortile interno",
        "rooms" => 3,
        "beds" => 2,
        "bathrooms" => 1,
        "apartment_size" => 100,
        "address" => "Via del Duomo, 33, Orvieto, Umbria, Italia",
        "latitude" => 42.717772,
        "longitude" => 12.112663,
        "image" => "https://www.pexels.com/it-it/foto/appartamento-cortile-155683/",
        "is_visible" => true
    ],
    [
        "id" => 40,
        "title" => "Bilocale accogliente in centro città",
        "rooms" => 2,
        "beds" => 1,
        "bathrooms" => 1,
        "apartment_size" => 50,
        "address" => "Piazza del Mercato, 12, Verona, Veneto, Italia",
        "latitude" => 45.434611,
        "longitude" => 10.992806,
        "image" => "https://www.pexels.com/it-it/foto/bilocale-mercato-184362/",
        "is_visible" => true
    ],
    [
        "id" => 41,
        "title" => "Monolocale accogliente con angolo cottura",
        "rooms" => 1,
        "beds" => 1,
        "bathrooms" => 1,
        "apartment_size" => 25,
        "address" => "Via dei Mille, 12, Trieste, Friuli Venezia Giulia, Italia",
        "latitude" => 45.649526,
        "longitude" => 13.776818,
        "image" => "https://www.pexels.com/it-it/foto/monolocale-accogliente-12345/",
        "is_visible" => true
    ],
    [
        "id" => 42,
        "title" => "Attico luminoso con terrazza e jacuzzi",
        "rooms" => 3,
        "beds" => 2,
        "bathrooms" => 2,
        "apartment_size" => 120,
        "address" => "Via delle Terrazze, 9, Bari, Puglia, Italia",
        "latitude" => 41.120654,
        "longitude" => 16.871872,
        "image" => "https://www.pexels.com/it-it/foto/attico-luminoso-231456/",
        "is_visible" => true
    ],
    [
        "id" => 43,
        "title" => "Appartamento con vista su Piazza Navona",
        "rooms" => 2,
        "beds" => 1,
        "bathrooms" => 1,
        "apartment_size" => 70,
        "address" => "Piazza Navona, 25, Roma, Lazio, Italia",
        "latitude" => 41.898600,
        "longitude" => 12.476872,
        "image" => "https://www.pexels.com/it-it/foto/appartamento-piazza-navona-341512/",
        "is_visible" => true
    ],
    [
        "id" => 44,
        "title" => "Rustico con camino nel cuore della Toscana",
        "rooms" => 4,
        "beds" => 2,
        "bathrooms" => 1,
        "apartment_size" => 95,
        "address" => "Via della Campagna, 14, Volterra, Toscana, Italia",
        "latitude" => 43.403395,
        "longitude" => 10.861663,
        "image" => "https://www.pexels.com/it-it/foto/rustico-toscana-412345/",
        "is_visible" => true
    ],
    [
        "id" => 45,
        "title" => "Villa esclusiva con piscina a sfioro",
        "rooms" => 7,
        "beds" => 6,
        "bathrooms" => 4,
        "apartment_size" => 400,
        "address" => "Via Belvedere, 5, Amalfi, Campania, Italia",
        "latitude" => 40.633334,
        "longitude" => 14.602924,
        "image" => "https://www.pexels.com/it-it/foto/villa-piscina-324512/",
        "is_visible" => true
    ],
    [
        "id" => 46,
        "title" => "Appartamento moderno vicino al Colosseo",
        "rooms" => 3,
        "beds" => 2,
        "bathrooms" => 2,
        "apartment_size" => 100,
        "address" => "Via San Giovanni, 8, Roma, Lazio, Italia",
        "latitude" => 41.890251,
        "longitude" => 12.492373,
        "image" => "https://www.pexels.com/it-it/foto/appartamento-moderno-812345/",
        "is_visible" => true
    ],
    [
        "id" => 47,
        "title" => "Bilocale romantico con balcone fiorito",
        "rooms" => 2,
        "beds" => 1,
        "bathrooms" => 1,
        "apartment_size" => 55,
        "address" => "Via delle Rose, 6, Bellagio, Lombardia, Italia",
        "latitude" => 45.958176,
        "longitude" => 9.256563,
        "image" => "https://www.pexels.com/it-it/foto/bilocale-romantico-412312/",
        "is_visible" => false
    ],
    [
        "id" => 48,
        "title" => "Casa colonica immersa nel verde",
        "rooms" => 5,
        "beds" => 3,
        "bathrooms" => 2,
        "apartment_size" => 150,
        "address" => "Via del Verde, 18, San Gimignano, Toscana, Italia",
        "latitude" => 43.467004,
        "longitude" => 11.042707,
        "image" => "https://www.pexels.com/it-it/foto/casa-colonica-verde-531234/",
        "is_visible" => true
    ],
    [
        "id" => 49,
        "title" => "Appartamento storico con soffitti a cassettoni",
        "rooms" => 4,
        "beds" => 3,
        "bathrooms" => 2,
        "apartment_size" => 140,
        "address" => "Via del Castello, 3, Trento, Trentino-Alto Adige, Italia",
        "latitude" => 46.074779,
        "longitude" => 11.121748,
        "image" => "https://www.pexels.com/it-it/foto/soffitti-storici-341264/",
        "is_visible" => true
    ],
    [
        "id" => 50,
        "title" => "Villa lussuosa con accesso privato al lago",
        "rooms" => 8,
        "beds" => 6,
        "bathrooms" => 5,
        "apartment_size" => 500,
        "address" => "Via del Lago, 1, Lecco, Lombardia, Italia",
        "latitude" => 45.856569,
        "longitude" => 9.397671,
        "image" => "https://www.pexels.com/it-it/foto/villa-lago-214875/",
        "is_visible" => true
    ]
];